# Generated by Django 2.1.5 on 2019-08-09 03:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amarform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('professional_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
